baseURL = "/"
title = "Saqib Mir"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 40

  [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 50

  [[menu.main]]
    name = "Git"
    url = "https://github.com/saqibmir1"
    weight = 60

  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/saqibmir1"
    weight = 10

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 20



[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
